- name: Initialize nodes
  hosts: inits
  tags:
    - initialize
  roles:
    - role: initialize
- name: Install k3s control-plane
  hosts: k8s_control_planes
  tags:
    - k3s-control-plane
  roles:
    - role: k3s-control-plane
- name: Install k3s worker
  tags:
    - k3s-worker
  roles:
    - role: k3s-worker

- name: Install system-upgrade-controller
  hosts: k8s_control_planes
  tags:
    - system-upgrade-controller
  roles:
    - role: system-upgrade-controller
