# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Enable overlay module
  command: modprobe overlay
  become: True

- name: Enable br_netfilter module
  command: modprobe br_netfilter
  become: True

- name: Load kernel module when machine started
  copy:
    src: k8s-modules-load.conf
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
  become: True

- name: Set sysctl params when machine started
  copy:
    src: k8s-sysctl.conf
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"
  become: True

- name: Check netfilter option configured as expected
  shell:
    cmd: sysctl --system
  register: sysctl_result
  failed_when: '"net.bridge.bridge-nf-call-iptables = 1" not in sysctl_result.stdout'
  become: True

# install containerd following official installation : https://github.com/containerd/containerd/blob/main/docs/getting-started.md#option-1-from-the-official-binaries
- name: Check containerd already installed
  shell:
    cmd: /usr/local/bin/containerd --version
  register: containerd_version_result
  # checking process should be always successful
  failed_when: False
  become: True

- name: Download and extract containerd tar
  unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  when: '"v1.6.6" not in containerd_version_result.stdout'
  become: True

- name: Ensure /usr/local/lib/systemd/system exists
  file:
    path: /usr/local/lib/systemd/system
    state: directory
    mode: '0755'
  become: True

- name: Download containerd systemctl service file
  get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/c4b1b368adc12bc63e0b4d0be723d8bc424627e3/containerd.service
    dest: /usr/local/lib/systemd/system/containerd.service
    mode: '0440'
  become: True

- name: Check nerdctl already installed
  shell:
    cmd: /usr/local/bin/nerdctl --version
  register: nerdctl_version_result
  # checking process should be always successful
  failed_when: False
  become: True

- name: Install nerdctl
  unarchive:
    src: https://github.com/containerd/nerdctl/releases/download/v0.21.0/nerdctl-0.21.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  when: '"0.21.0" not in nerdctl_version_result.stdout'
  become: True

- name: Check runc already installed
  shell:
    cmd: /usr/local/sbin/runc --version --version
  register: runc_version_result
  # checking process should be always successful
  failed_when: False
  become: True

- name: Download runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64
    dest: /tmp/runc.amd64
    mode: '0550'
  when: '"v1.1.3" not in runc_version_result.stdout'
  become: True

- name: Install runc
  command: install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc
  when: '"v1.1.3" not in runc_version_result.stdout'
  become: True

- name: Remove runc.amd64 file
  file:
    path: /tmp/runc.amd64
    state: absent
  when: '"v1.1.3" not in runc_version_result.stdout'
  become: True

- name: Ensure /opt/cni/bin exists
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'
  become: True

- name: Check cni plugins already installed
  shell:
    cmd: /opt/cni/bin/bridge -v
  register: cni_bridge_version_result
  # checking process should be always successful
  failed_when: False
  become: True

- name: Download and extract cni plugins
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /opt/cni/bin
    remote_src: yes
  # NOTE: bridge version is output to stderr for some reason 
  when: '"v1.1.1" not in cni_bridge_version_result.stderr'
  become: True

- name: Enable containerd systemctl service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: True
