# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Enable overlay module
  command: modprobe overlay
  become: True

- name: Enable br_netfilter module
  command: modprobe br_netfilter
  become: True

- name: Load kernel module when machine started
  copy:
    src: k8s-modules-load.conf
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
  become: True

- name: Set sysctl params when machine started
  copy:
    src: k8s-sysctl.conf
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"
  become: True

- name: Check netfilter option configured as expected
  shell:
    cmd: sysctl --system
  register: sysctl_result
  failed_when: '"net.bridge.bridge-nf-call-iptables = 1" in sysctl_result.stdout'
  become: True

# install containerd following official installation : https://github.com/containerd/containerd/blob/main/docs/getting-started.md#option-1-from-the-official-binaries
- name: Download and extract containerd tar
  ansible.builtin.unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: True

- name: Download containerd systemctl service file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/c4b1b368adc12bc63e0b4d0be723d8bc424627e3/containerd.service
    dest: /usr/local/lib/systemd/system/containerd.service
    mode: '0440'
  become: True

- name: Download runc
  ansible.builtin.get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64
    dest: /usr/local/sbin/runc
    mode: '0550'
  become: True

- name: Install runc
  command: install -m 755 runc.amd64 /usr/local/sbin/runc
  become: True

- name: Download and extract cni plugins
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /opt/cni/bin
    remote_src: yes
  become: True

- name: Enable containerd systemctl service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: True
