# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
- name: Install required libraries
  apt:
    pkg:
    - apt-transport-https=2.4.5
    - ca-certificates=20211016
    - curl=7.81.0-1ubuntu1.3
    state: present
  become: True

- name: Download the Google Cloud public signing key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    mode: '0444'
  become: True

- name: Add kubernetes apt list
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: "0444"
  become: True

- name: Install commands required in kubernetes
  apt:
    pkg:
    - kubeadm=1.24.2-00
    - kubelet=1.24.2-00
    - kubectl=1.24.2-00
    state: present
    update_cache: True
  become: True

# TIPS: 2022/07/19 - force use cgroup v1 because cgroup v2 & containerd & kubeadm 1.24 may ends up crashing kube-apiserver & etcd
# cgroup v2 is default after ubuntu 21.10
- name: Check if cgroup v1 is used
  shell:
    cmd: cat /etc/default/grub
  register: grub_result
  become: True

- name: Force using cgroup v1 not cgroup v2
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=false"'
  when: '"systemd.unified_cgroup_hierarchy=false" not in grub_result.stdout'
  become: True

- name: Update grub 
  shell:
    cmd: update-grub
  when: '"systemd.unified_cgroup_hierarchy=false" not in grub_result.stdout'
  become: True

- name: Reboot node
  reboot:
    reboot_timeout: 300 # 5min
  when: '"systemd.unified_cgroup_hierarchy=false" not in grub_result.stdout'
  become: True

- name: Set swapoff
  command: swapoff -a
  when: '"systemd.unified_cgroup_hierarchy=false" not in grub_result.stdout'
  become: True
