# Enable progressive delivery via argo-cd (not deploying manifest via ansible)
# https://argo-cd.readthedocs.io/en/stable/#getting-started
- name: Apply argo-cd manifest
  shell:
    cmd: |
      kubectl create namespace argocd; \
      kubectl apply -n argocd -f https://github.com/argoproj/argo-cd/raw/v2.11.3/manifests/install.yaml

# After argocd is instaled configure settings like below to install your kubernetes manifests

#project: default
#source:
#  repoURL: 'https://github.com/go-zen-chu/home-k8s.git'
#  path: overlays/prod
#  targetRevision: HEAD
#destination:
#  server: 'https://kubernetes.default.svc'
#syncPolicy:
#  automated:
#    prune: true
